[package]
name = "mev-share-sse"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = """
MEV-share Server Side Events support in rust
"""

[dependencies]
ethers-core.workspace = true

## async
async-sse = "5.1"
reqwest = { version = "0.11", features = ["stream", "json"] }
futures-util = { version = "0.3", features = ["io"] }
http-types = { version = "2.12", default-features = false }

## misc
bytes = "1.4"
pin-project-lite = "0.2"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json.workspace = true
tokio = { version = "1", features = ["time"] }
tracing = "0.1"

[dev-dependencies]
tokio = { version = "1", features = ["macros", "rt", "rt-multi-thread"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["env-filter", "fmt"] }
