[package]
name = "examples"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
mev-share-sse = { path = "../crates/mev-share-sse" }
mev-share-rpc-api = { path = "../crates/mev-share-rpc-api", features = ["client", "server"] }

## async
tokio = { version = "1", features = ["macros", "rt", "rt-multi-thread"] }
futures-util = { version = "0.3" }
jsonrpsee = { version = "0.18", features = ["client", "async-client"] }
tower = "0.4.13"

## eth 
ethers-core.workspace = true
ethers-signers.workspace = true
tracing-subscriber = { version = "0.3", default-features = false, features = ["env-filter", "fmt"] }


[[example]]
name = "sse"
path = "sse.rs"
[[example]]
name = "rpc-client"
path = "rpc-client.rs"